### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#1348]
https://usaco.guide/gold/lis?lang=cpp#problem-joi-16-matryoshka

someone reported via email that this problem doesn't have english translation?

**Comment by JonathanSawyer** [comment]
大変ですね

**Comment by SansPapyrus683** [comment]
soooo any update on this issue?

**Comment by Aadit-Ambadkar** [comment]
Nothing has been done about this...

**Comment by SansPapyrus683** [comment]
asked a friend on discord
this is what they gave me
```
You are ordering N number of  matryoshka dolls. They each have some diameterR and some height H. However, due to some issues, not all of the matryoshka dolls will be delivered at once. Dolls will come early that have a diameter above the value A and a height below B. The values of A and B will be variable. So, you decide to order some number Q of matryoshka dolls. You are tasked with writing a program that will find the minimum number of matryoshka dolls that will not fit inside any other matryoshka dolls? 

Input: 
The first line will be the N number of matryoshka dolls you have ordered followed by the number Q, (divided by a space) of matryoshka dolls that will come early. 
The following N lines of input will have the sets of the diameter R and height H (divided by a space) of the individual matryoshka dolls ordered.
After that, the following Q lines of input will be the specifications of the matryoshkas that will arrive early. First is A, minimum diameter, followed by B,(divided by a space) the maximum height of the matryoshkas. 

Output:
The output should consist of Q number of lines. Each line j, where (0 <= j <= Q), the set of (A_j, B_j) . After putting all the matryoshkas that can fit inside other matryoshka dolls, the output should be the number of matryoshkas that will not fit inside any matryoshkas.
```

**Comment by SansPapyrus683** [comment]
ok
i asked the friend and managed to clear up the problem a bit more

You are ordering N matryoshka dolls. They each have a diameter R and a height H.
A matryoshka doll will only fit inside another if the former's height and width
are both less than the latter's.

You also have Q queries. Each of these Q queries has two arguments: A and B.
For each of the queries, you need to answer the following question:
Among the set of dolls that have minimum diameter A and maximum height B, how can you fit these dolls in each other, making "towers" of dolls, so that the total number of "towers" is minimal?

## Input
The first line will contain N and Q.
The next N lines will contain R and H for each of the dolls.
The next Q lines will contain A and B for each of the queries.

## Output
Q lines, each containing the answer for the respective query.

## Example Input
```
7 3
9 5
3 7
10 6
5 10
2 6
10 10
4 1
10 5
3 5
3 9
```

## Example Output
```
0
1
2
```

## Example Output Explanation
For the first query, there are no dolls that have minimum diameter 10 and maximum height 5, so the answer is 0.

For the second query, only dolls number 1 and 7 query's requirements, and doll 7 fits in doll 2, so the answer is 1.

For the last query, dolls number 1, 2, 3, and 7 satisfy the requirements. Doll 7 fits in doll 1, and doll in fits in doll 3.
Doll 2 does not fit in any of the other dolls. Thus, the answer for this query is 2.

**Comment by SansPapyrus683** [comment]
so how should i put this in the guide
putting it at the end of the problems would be kinda awkard
how about i just up and make this a focus problem lol

**Comment by thecodingwizard** [comment]
I'm fine with putting it at the end (in a spoiler perhaps)? or we can make a custom page for it but that's a bit more involved

**Comment by SansPapyrus683** [comment]
fixed
