### ISSUE TITLE
International Translations

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2775]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/mst?lang=cpp
**Module**: ALL
**Topic**: Suggestion
**Message**: 
Hello!
I'm an IB high school student in Shanghai, China. These days my teacher introduced usaco.guide as a wonderful website for studying on one's own. I really like this website, and I also have some suggestions.

As I'm the president of the Computer Science club in my school, one of our major activity is to learn OI together. However, for some of our club members, especially those who are new to OI, they have trouble reading the English pages on usaco.guide. From this phenomenon, I get one idea, that maybe I can do some translation work to usaco.guide, so that it can serve more students. I think not only Chinese but also other languages may be considered. A button to switch the language may be added on usaco.guide as well.

**Comment by SansPapyrus683** [comment]
@thecodingwizard what web dev implications would this have? if it can be implemented i'd be really onboard with CN support

**Comment by thecodingwizard** [comment]
Rather nontrivial. Gatsby does have i18n: https://www.gatsbyjs.com/docs/how-to/adding-common-features/localization-i18n/ but we 100% did not build the website with translation support in mind.

I think the most feasible way to do this right now would be to fork the repository and change the important files (I can point you in the right direction). Mostly under `content/`.

However, if there's strong and continued community support behind translating very large sections of the USACO Guide, it is indeed possible to implement a long-term translation solution with a single repository. It would just take a bit of time :)

**Comment by Cubik65536** [comment]
I used to have a plan for maintaining a Chinese version of the USACO Guide, but there were very few people interested in this back then. I think it will be very important that more people can involve in the project because, in my experience from doing some other translation projects, just a few people together cannot maintain the passion needed for such a huge and mostly, a bit boring (in terms of doing the translation), project. So we sure need to try to reach out to more people for maintaining the project, even in a fair bit of time, so I think we (not CPI, but rather some people like me), as a not very known project starter, need some help (perhaps from CPI) for reaching out to more people interested in this project.
Also, I think it will be a good plan to start by maintaining a fork of the USACO Guide, then try to implement a translation solution to this main site after we see how it goes.
And if there is a plan for implementing these, I'd like to be a part of it.

**Comment by bqi343** [comment]
Discussion moved to #2788.

**Comment by SansPapyrus683** [comment]
nvm should probably leave this open

**Comment by thecodingwizard** [comment]
I'm not sure if we will have the bandwidth to do this anytime soon, so I'm thinking I will close this issue for now. Please feel free to reopen / comment something if you feel otherwise!
