### ISSUE TITLE
Country-specific ordering

### ISSUE THREAD

**Issue by dolphingarlic** [cpinitiative/usaco-guide#287]
Basically what @eohomegrownapps suggested.

We ideally want to allow other countries to customize the USACO Guide and tailor it to their own national training camp. Such customizations should include:

- Custom landing page
- Custom domain name
- Add/remove modules, sections
- Custom branding / logo / styling (?)

**Comment by thecodingwizard** [comment]
It's actually fairly doable... just fork the repo and modify ordering.ts. (in fact there might even be a way to do this without having to fork the repo.)

Country-specific modules can then be included/excluded using ordering.ts.

If there's interest in this let me know!

**Comment by thecodingwizard** [comment]
Okay so there's a number of options for country-specific customization:

1. Allow people to fork the repo and deploy by themselves
2. Add a new branch to the repo and deploy it through CPI
3. Add a new repo to CPI organization and deploy it through CPI

I prefer options 2 & 3 because the deployment is a bit nontrivial (search, gatsby build, etc)

One potential workflow can be:

- any content changes that aren't country-specific go to main usaco-guide repo (ex. updating "Intro to DP")
- any country-specific content goes to the country repo (ex. info on a country's national camp selection process)
- any country-specific modifications goes to the country repo (ex. changing the homepage)
- user progress is stored on a shared database
- The country repo will need to "sync" itself with the main repo frequently

To do the syncing, someone can either manually run `git pull`, fix merge conflicts, and then run `git push`. Alternatively, we can set up an automated system to do that for us (when main repo gets a new commit, automatically update forks): https://github.com/wei/pull However, merge conflicts might be an issue (?).
