### ISSUE TITLE
Contact Form Submission - Suggestion (Notes on Resources)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#2954]
Someone submitted the contact form!

**URL**: https://usaco.guide/silver/func-graphs?lang=cpp
**Module**: None
**Topic**: Suggestion
**Message**: 
The feature to add Notes would be great. Then I can not only mark something for later, but also add a note to it that what have I left to do for later. 

I mean, say, for example,  while reading a pdf (from the resource section), I couldn't understand any sub-topic, I can add a note that in this pdf I need to redo this sub-topic, etc.

**Comment by bqi343** [comment]
For notes on solutions, you can see https://github.com/cpinitiative/usaco-guide/issues/1798. It might be worth adding similar functionality for resources.

**Comment by bqi343** [comment]
It would be nice to support markdown. Maybe https://usaco.guide/editor/ could be repurposed for this.

**Comment by thecodingwizard** [comment]
While this is something that is possible, I'm not sure if it's worth it for us to support this functionality since it seems like a lot of technical effort (both to build and to maintain), and it seems like other note-taking apps can be used alongside the USACO Guide to solve this problem?

I'm going to close this issue for now, but if other people strongly feel this would be a valuable addition to the USACO Guide, please feel free to re-open so we can discuss!
