### ISSUE TITLE
Contact Form Submission - Suggestion (view user solutions should open a new tab)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#3778]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/shortest-paths?lang=cpp
**Module**: None
**Topic**: Suggestion
**Message**: 
Hi there, thanks for all your work!
It is truly appreciated. I have one minor request can we support opening view user solutions in another tab? just like view internal solution. Thanks

**Comment by bqi343** [comment]
Not sure whether there's an easy way to do this at the moment (`navigate` doesn't seem to have an option to open in a new tab: https://reach.tech/router/api/navigate), but would be easy after #2971 is implemented.

**Comment by bqi343** [comment]
@thecodingwizard any thoughts? is this easy to do?

**Comment by thecodingwizard** [comment]
I don't think this is easy to do with our current setup because we're passing in problem data into the `navigate` function (and based on what you found, it doesn't look like we can do this while opening a new tab).

It would probably be easiest to just implement #2971. It's probably not too difficult to do so; a rough outline of steps would probably be:

1. Create a `userSolutionTemplate.tsx` file similar to https://github.com/cpinitiative/usaco-guide/blob/master/src/templates/solutionTemplate.tsx . Move the content in `problem-solutions.tsx` https://github.com/cpinitiative/usaco-guide/blob/master/src/pages/problem-solutions.tsx into the new template file. Rather than getting `ProblemInfo` from `props.location.state`, we should get it from `props.data` (similar to how `solutionTemplate.tsx` gets its data).
2. Modify `gatsby-node.ts` to create a new page for every problem's user solutions. Similar to this: https://github.com/cpinitiative/usaco-guide/blob/556fb6235c582786509e4e9962c675a266285d90/gatsby-node.ts#L412 but instead of only creating a page if an internal solution exists, always create a page. The url could be something like `/problems/[problem-id]/user-solutions` or something. Make sure to pass in the needed `ProblemInfo` into the template.
3. Update links to point to the appropriate URL rather than using `navigate`.

**Comment by Vinceyou1** [comment]
I just submitted a PR for this issue: https://github.com/cpinitiative/usaco-guide/pull/3837
