### ISSUE TITLE
Clicking on USACO Guide Icon when Logged In

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#3779]
If you are logged in and at https://usaco.guide/dashboard, and then you click the USACO Guide icon on the top-left, you are briefly taken to the homepage but then back to the dashboard. The intended behavior is to just be taken to the homepage.

**Comment by shaubby** [comment]
@bqi343 
Currently the button built to take you to the homepage if you are not logged in, but if you are it will take you to the dashboard. However, this is done somewhat inefficiently because the icon will always take you to the homepage and then if you are logged in it will redirect you to the dashboard. I can either make icon always go to the homepage even if you are logged in, or I can keep the existing functionality but change it so that it links directly to the dashboard if you are logged in, without a redirect.

**Comment by bqi343** [comment]
> Currently the button built to take you to the homepage if you are not logged in, but if you are it will take you to the dashboard.

This doesn't seem true? If you are not logged in, it will take you to the homepage if you are on the dashboard, and to the dashboard from the homepage. When logged in, the intended behavior is the same (but the current behavior is not).

**Comment by shaubby** [comment]
The same thing is not happening for me.

When I am on the dashboard and logged in, it takes me to the homepage and back to the dashboard.
https://drive.google.com/file/d/1KxrHvhOgY8V8q8Bz3AIO3MmmL4DU3ff8/view?usp=sharing

When I am not logged in, it just takes me to the homepage.
https://drive.google.com/file/d/1NMkfL_Vx6xZCeDHm41boI98_m6reg5EZ/view?usp=sharing

**Comment by bqi343** [comment]
That's the same as what I see. I meant that if you are not logged in and you repeatedly click the button, it will toggle between  the homepage and the dashboard.

**Comment by shaubby** [comment]
Ok I will get to work fixing that.
