### ISSUE TITLE
Contact Form Submission - Minor Mistake (Silver - Two Pointers)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4106]
Someone submitted the contact form!

**URL**: https://usaco.guide/silver/two-pointers?lang=cpp
**Module**: Silver - Two Pointers
**Topic**: Minor Mistake
**Message**: 
Incorrect solution for question 3 (the answers seem inverted).

**Comment by bqi343** [comment]
<img width="865" alt="Screenshot 2023-12-24 at 12 08 38 AM" src="https://github.com/cpinitiative/usaco-guide/assets/21228024/1d370215-509e-46c5-9e38-982542f4473b">

It looks fine to me. The choice you're supposed to select is the third choice, which is why it's marked as "correct."

That being said, I'm not sure why the solutions to the first two choices mention sorting the array.

**Comment by SansPapyrus683** [comment]
i think they didn't see that it was supposed to be "which _isn't_ true"

**Comment by SansPapyrus683** [comment]
ben do you think the first two answers should be adjusted or smth

**Comment by bqi343** [comment]
yes
