### ISSUE TITLE
Problem section doesn't work

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4161]
Someone submitted the contact form!

**URL**: https://usaco.guide/problems/
**Module**: None
**Topic**: Website Bug
**Message**: 
Problem section doesn't work

**Comment by bqi343** [comment]
https://github.com/cpinitiative/usaco-guide/issues/86#issuecomment-1873341366

@thecodingwizard Will #4157 fix this? and if so, are you planning to increase the number of operations for this month after that's merged?

**Comment by devo1ution** [comment]
Yeah, the issue was that instantsearch v7 only provided an api to refine item by item and not a whole list at once, so filtering by problem status was insanely expensive (because we would have to filter each objectId one by one, and there's thousands of them); however, I eventually got a workaround using `setIndexUiState` which basically replicates the old refine behavior, but not before we exceeded quota 😓

**Comment by bqi343** [comment]
I'm confused, I thought we hadn't migrated to v7 yet.

**Comment by devo1ution** [comment]
Yeah but I accidentally incurred these ops during local testing 😭

**Comment by SansPapyrus683** [comment]
ok it works now!!!
