### ISSUE TITLE
usaco.guide editor light mode issues

### ISSUE THREAD

**Issue by danielzsh** [cpinitiative/usaco-guide#4316]
<img width="1470" alt="image" src="https://github.com/cpinitiative/usaco-guide/assets/65467530/b8e1a762-b5b4-4919-bf64-80baab538497">

**Comment by danielzsh** [comment]
btw, @thecodingwizard: have we considered using something like this? https://github.com/jjranalli/nightwind?tab=readme-ov-file It seems pretty useful, as usually dark mode color conversions end up being just [color_code] -> [1000 - color_code] (e.g. bg-gray-100 becomes bg-gray-900)

**Comment by thecodingwizard** [comment]
I vaguely recall Tailwind CSS writing something about this: blindly inverting colors doesn't always yield good results; sometimes colors need to be hand-picked for dark mode, which is why they do not recommend automatically inverting colors.

We should upgrade our Tailwind version though: the latest tailwind version has more colors for dark mode (`950`?) which should help make things prettier.
