### ISSUE TITLE
Absence of the Sidebar (for changing Divsions and sections)

### ISSUE THREAD

**Issue by anshkush92** [cpinitiative/usaco-guide#4484]
![image](https://github.com/cpinitiative/usaco-guide/assets/78142732/b32e7740-00bb-42b8-9c17-2c8b93320e79)

After clicking the greyish area, there is no way to change the divisions or sections directly (I don't know if it is a bug or feature)  but after refreshing it comes again (sidebar)

![image](https://github.com/cpinitiative/usaco-guide/assets/78142732/f1b619c3-55d8-4621-9258-dc043212570a)

**Comment by bqi343** [comment]
@SansPapyrus683 @shine00chang @Vinceyou1 consequence of #4479. Can this be reverted or fixed?

**Comment by shine00chang** [comment]
I'll look into it.

**Comment by shine00chang** [comment]
The issue is that I accidentally committed my changes for #3998.
I've opened #4485 reverting those changes

**Comment by bqi343** [comment]
Closed by https://github.com/cpinitiative/usaco-guide/pull/4485

**Comment by ghost** [comment]
Give users manual control over hiding the sidebar, regardless of screen size. A toggle button would be ideal — even on large screens. On an ultrawide monitor, I often work in split screen and want the sidebar hidden, but in full screen, I prefer it visible. Right now, there's no way to make that choice myself.

<img width="2556" height="1007" alt="Image" src="https://github.com/user-attachments/assets/7c3a351d-9318-4e25-877a-a307b7c6d462" />

It would be great to have more flexible sidebar behavior options:
Option 1: Show the sidebar on cursor hover, allowing it to stay hidden until needed.

Option 2: Allow persistent open/close control, similar to how VS Code handles its sidebar — users can explicitly toggle it and have that choice respected.

These options would let users customize the UI based as they wise instead of being locked into screen-size-based behavior for larger display like HD(1920x1080) or higher.
