### ISSUE TITLE
Contact Form Submission - Website Bug (Gold - (Optional) Hashmaps)

### ISSUE THREAD

**Issue by maggieliu05** [cpinitiative/usaco-guide#4588]
Someone submitted the contact form!

**URL**: https://usaco.guide/gold/hashmaps?lang=cpp
**Module**: Gold - (Optional) Hashmaps
**Topic**: Website Bug
**Message**: 
why does the website have white text on a white background. See here: https://usaco.guide/gold/hashmaps?lang=cpp

**Comment by frogeyedpeas** [comment]
I submitted this. Here is a screenshot 
<img width="1766" alt="Screenshot 2024-07-07 at 1 12 15 PM" src="https://github.com/cpinitiative/usaco-guide/assets/5061556/37dd42c6-2851-4ce0-b062-617bfc9d7ef5">

**Comment by frogeyedpeas** [comment]
Same page highlighted now. 

<img width="1169" alt="Screenshot 2024-07-07 at 1 13 58 PM" src="https://github.com/cpinitiative/usaco-guide/assets/5061556/75fb0001-c149-491c-a516-2812729b259f">

**Comment by bqi343** [comment]
Can't reproduce. Can you reproduce on other devices / browsers / modules? If you change the theme between light and dark does it work? Are there any errors in the console?

**Comment by frogeyedpeas** [comment]
Hi, its still a problem. the color scheme is broken on pretty much every tab in the gold section. Here is a link to another broken page:

https://usaco.guide/gold/gold-conclusion?lang=cpp#what-now

<img width="1159" alt="Screenshot 2024-12-21 at 10 16 07 PM" src="https://github.com/user-attachments/assets/1dda677d-dee9-4976-9fd1-56dbc75bb017" />



JS console suggests there might be something wonky going on with react but I have reason to believe this is NOT the cause of the bug (See below): 

<img width="602" alt="Screenshot 2024-12-21 at 10 13 50 PM" src="https://github.com/user-attachments/assets/840575fa-4cb4-4aea-9da6-3ca49d800143" />
<img width="663" alt="Screenshot 2024-12-21 at 10 13 56 PM" src="https://github.com/user-attachments/assets/aab291bb-af72-445c-8056-577fb5e88701" />


It appears that the problem is only present when the color scheme is set to "System" or "Dark Mode". The problem is not present in "Light Mode". It appears that changing the mode does NOT change the text color, only the background color.

I confirmed the same React Errors in console appear in "Light Mode" so I do not believe the error has to do with those console messages.

**Comment by frogeyedpeas** [comment]
Requesting reopen @maggieliu05 @bqi343

**Comment by bqi343** [comment]
@frogeyedpeas Can you reproduce this across modules in other divisions? What if you use a different browser or device?

Are there any errors in the console other than "#418" and "#423"?

@thecodingwizard Do you have any clue? I haven't heard of anyone else experiencing this issue, and I can't reproduce.

**Comment by thecodingwizard** [comment]
The hydration errors are expected (an unrelated bug on our part). I'm also unable to reproduce the dark mode issue. My guess is some extension is messing with the website (try incognito?), or some browser version

**Comment by frogeyedpeas** [comment]
@thecodingwizard  that was a good hunch; after some testing it seems to me that the website font colors break when the extension "screenshader" is installed https://chromewebstore.google.com/detail/screen-shader-smart-scree/fmlboobidmkelggdainpknloccojpppi

This is an extremely popular extension and I haven't had issues with it and any website until I encountered the usaco.guide gold page. 

I'm not sure how complex of a fix this will be. I suppose someone can try to clone the usaco.guide repo and strip it down as much as possible to find a "simplest version of the site" whose color scheme breaks under screenshader and then try to evaluate why that is happening.

**Comment by bqi343** [comment]
judging from the reviews this seems like a known issue of the extension
