### ISSUE TITLE
practice tests

### ISSUE THREAD

**Issue by darren-yao** [cpinitiative/usaco-guide#868]
occasional practice tests for each division (problem quality doesn't need to be great, but at least make it representative)

-Apple Method

**Comment by bqi343** [comment]
are past USACO contests even "representative" of future ones :/

**Comment by SansPapyrus683** [comment]
Probably not- maybe pull some CF ones that might be representative instead? I know plenty of people who've done all the USACO problems, but not a single one who's done all the CF ones.

**Comment by Shad0wSeven** [comment]
I was in the discord when the person requested this, essentially they wanted something like an AoPS style Mock Test, since most of you guys actually write real problems for USACO, mostly because they abused the editorials before solving and ran out of USACO to solve. 

tbh it's not a bad idea, but I personally thought it might be too much to ask, but I mean if you guys dropped a mock contest every month or so and published editorials a week later that could be pretty fun even if the quality was low

**Comment by bqi343** [comment]
[CCC](https://www.compcs.codes/index) already does this.
