### ISSUE TITLE
View Code Submissions

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#999]
View a list of the code snippets that you have submitted.

**Comment by thecodingwizard** [comment]
where should we put this? (what would people do with this information?)

**Comment by bqi343** [comment]
Maybe it suffices for the row of the corresponding problem tables to be colored in a different way when you submit a solution, so can easily tell that I've added code for that problem without having to click the buttons.

**Comment by thecodingwizard** [comment]
Okay. I'm thinking I'll add a green check mark to the right of the problem name if you've submitted a solution? (with a tooltip to explain what it means)

**Comment by thecodingwizard** [comment]
@jeffreymeng thoughts on how we can do this? seems expensive to do one doc read per problem. Perhaps we should cache this information somewhere (like a map of problem ID ==> list of problem solution ID's in a user doc)?

We may need to seriously be careful about the 1mb limit though.

**Comment by jeffreymeng** [comment]
Maybe just upload the files to firebase storage?
That’s cheaper and has no limit


Best,
Jeffrey Meng

--
Jeffrey Meng ***@***.*** | jeffkmeng.com

**Comment by thecodingwizard** [comment]
I didn't mean the code itself, I meant the user data document that stores IDs of all the code solutions

**Comment by jeffreymeng** [comment]
Whoops. I only saw your message in my email; I didn't realize there was stuff before it.

First of all, if we're already storing whether a user has solved a problem, it doesn't seem like it would be that much worse to also store the ID to the solution. However, it might suffice to simply store that a solution exists (like "solved-with-solution" instead of "solved" or something).

Furthermore, if we want to decrease the storage size, it seems like it would be much better to focus on the keys we use. For example, in the userProgressOnProblems object, the key is the URL to the problem, which is outrageously long. Shortening something like "http://www.usaco.org/index.php?page=viewproblem2&cpid=664" (57 characters) to potentially only 5-10 characters would more than make up for any storage concerns related to storing an extra ID for each solved problem with a code submission.
